---
- name: Configure cluster
  block:
    - name: Set API VIP
      shell: "aicli update cluster -P api_vip={{ api_vip }} {{ cluster_name }}-day2"
      
    - name: Wait until cluster is ready to be installed
      shell: "aicli list cluster | grep {{ cluster_name }}-day2 |  cut -d '|' -f4 | tr -d ' '"
      register: cluster_ready
      until: cluster_ready.stdout == "ready"
      retries: 100
      delay: 30

    - name: Install cluster
      shell: "aicli start cluster {{ cluster_name }}-day2"
  environment:
    AI_URL: "{{ ai_url }}"

