---
- name: Deploy clusters with assisted installer
  hosts: provisioner
  roles:
    - role: create-cluster
      tags: create-cluster
    - role: modify-iso
      tags: modify-iso
    - role: deploy-cluster 
      tags: deploy-cluster

